name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "Images/f.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "Images/f.png"

flutter:
  uses-material-design: true


  assets:
    - Images/f.png
    - Images/images.jpg
